databases:
  - name: greenconnect-db
    databaseName: laravel
    user: laravel
    plan: free

services:
  - type: web
    name: greenconnect2
    env: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: sqlite
      - key: LOG_CHANNEL
        value: stderr
